name: Code Quality

on:
  push:
    branches: [main, develop, feature/*]
  pull_request:
    branches: [main, develop]

# ============================================================================
# BILLING OPTIMIZATION
# ============================================================================
# This workflow is optimized for GitHub Actions billing:
# - ubuntu-latest: 1x multiplier (standard rate)
# - macos-15: 10x multiplier (use only when Xcode is required)
#
# SwiftLint and SwiftFormat run on Ubuntu to minimize costs.
# For private repos with 2,000 min/month free tier, this saves ~90% on
# quality checks compared to running on macOS.
# ============================================================================

jobs:
  swiftlint:
    name: SwiftLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict
        env:
          DIFF_BASE: ${{ github.base_ref }}

  swiftformat:
    name: SwiftFormat
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install SwiftFormat
        run: |
          # Download SwiftFormat binary for Linux
          SWIFTFORMAT_VERSION="0.54.6"
          curl -sL "https://github.com/nicklockwood/SwiftFormat/releases/download/${SWIFTFORMAT_VERSION}/swiftformat_linux.zip" -o swiftformat.zip
          unzip -q swiftformat.zip
          chmod +x swiftformat_linux
          sudo mv swiftformat_linux /usr/local/bin/swiftformat

      - name: Check formatting
        run: swiftformat --config .swiftformat --lint .

  markdown-links:
    name: Validate Markdown Links
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'no'
          config-file: '.github/markdown-link-check-config.json'
          check-modified-files-only: 'no'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
