name: Tests

on:
  push:
    branches: [main, develop, feature/*]
  pull_request:
    branches: [main, develop]

jobs:
  test-macos:
    name: Build (macOS)
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.0.app/Contents/Developer

      - name: Display Swift version
        run: swift --version

      - name: Run tests
        run: swift test --parallel

  test-linux:
    name: Build (Linux)
    runs-on: ubuntu-latest
    container:
      image: swift:6.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display Swift version
        run: swift --version

      - name: Run tests
        run: swift test --parallel
