#!/usr/bin/env swift
// ARCDevTools - API Key Obfuscation Codegen
// Version: 1.0.0
//
// Generates a lightly-obfuscated `[UInt8]` literal for a string, so a
// client-public key (e.g. a RevenueCat or Firebase SDK key) does not appear as
// a plain `String` literal in the binary. Reconstruct at runtime with
// `ARCStorage.ConfigurationValue.deobfuscated(_:)`.
//
// ⚠️  This is LIGHT OBFUSCATION — a speed-bump against casual `strings`-style
//     scraping, NOT a secret store. Anything shipped in an app binary is
//     recoverable. Never use this for server-side secrets; proxy those through
//     a backend (Cloud Function + Secret Manager).
//
// Usage:
//   swift scripts/key-obfuscator.swift "appl_yourRevenueCatKey"
//   swift scripts/key-obfuscator.swift "appl_yourKey" --name rcAPIKey
//
// Paste the printed declaration into a committed source file in your app.

import Foundation

func obfuscatedTerms(for key: String) -> [String] {
    Array(key.utf8).map { byte in
        if Bool.random() {
            // (byte - delta) + delta — needs delta <= byte so the literal fits in UInt8.
            let delta = UInt8.random(in: 0 ... byte)
            return String(format: "0x%02X + 0x%02X", byte - delta, delta)
        } else {
            // (byte + delta) - delta — needs delta <= 255 - byte so the sum fits in UInt8.
            let delta = UInt8.random(in: 0 ... (255 - byte))
            return String(format: "0x%02X - 0x%02X", byte + delta, delta)
        }
    }
}

func declaration(name: String, terms: [String]) -> String {
    """
    // Generated by ARCDevTools/scripts/key-obfuscator.swift — light obfuscation, not a secret store.
    // Reconstruct at runtime: ConfigurationValue.deobfuscated(\(name))
    let \(name): [UInt8] = [\(terms.joined(separator: ", "))]
    """
}

let args = Array(CommandLine.arguments.dropFirst())
let exe = (CommandLine.arguments.first as NSString?)?.lastPathComponent ?? "key-obfuscator.swift"

guard let key = args.first, !key.isEmpty, !key.hasPrefix("--") else {
    FileHandle.standardError.write(Data("""
    Usage: swift \(exe) "<key>" [--name <identifier>]

      <key>            The string to obfuscate (quote it).
      --name <ident>   Name for the generated constant (default: obfuscatedKey).

    """.utf8))
    exit(EXIT_FAILURE)
}

guard String(data: Data(Array(key.utf8)), encoding: .utf8) == key else {
    FileHandle.standardError.write(Data("error: input is not valid UTF-8\n".utf8))
    exit(EXIT_FAILURE)
}

var name = "obfuscatedKey"
if let i = args.firstIndex(of: "--name"), i + 1 < args.count, !args[i + 1].hasPrefix("--") {
    name = args[i + 1]
}

let terms = obfuscatedTerms(for: key)

// Self-check: evaluate the generated arithmetic and confirm it round-trips.
let reconstructed: [UInt8] = terms.map { term in
    let parts = term.split(separator: " ")
    let lhs = UInt8(parts[0].dropFirst(2), radix: 16) ?? 0
    let rhs = UInt8(parts[2].dropFirst(2), radix: 16) ?? 0
    return parts[1] == "+" ? lhs + rhs : lhs - rhs
}
guard String(data: Data(reconstructed), encoding: .utf8) == key else {
    FileHandle.standardError.write(Data("error: internal consistency check failed — please retry\n".utf8))
    exit(EXIT_FAILURE)
}

print(declaration(name: name, terms: terms))
