#!/bin/bash
# =============================================================================
# ARC Labs Studio - Protect Sensitive Files (PreToolUse)
# =============================================================================
# Blocks Edit/Write operations on files that should never be directly modified:
# - Secrets and credentials (.env, .pem, .p12, .p8, .key)
# - Apple provisioning and certificates (.mobileprovision, .cer, AuthKey_*.p8)
# - Generated/lock files (Package.resolved, Podfile.lock)
# - Xcode project file (project.pbxproj — edit via Xcode, not text)
# - Fastlane auth configs (Matchfile, Appfile)
#
# Input: PreToolUse JSON on stdin (tool_name, tool_input)
# Output: JSON with deny decision if file is protected
# =============================================================================

set -euo pipefail

INPUT=$(cat)

# Only process Edit and Write tool calls
TOOL_NAME=$(echo "$INPUT" | jq -r '.tool_name // empty')
if [[ "$TOOL_NAME" != "Edit" && "$TOOL_NAME" != "Write" ]]; then
    exit 0
fi

# Extract the file path
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')
if [[ -z "$FILE_PATH" ]]; then
    exit 0
fi

FILENAME=$(basename "$FILE_PATH")
REASON=""

# --- Secrets and credentials ---
if [[ "$FILENAME" == ".env" || "$FILENAME" == *.env || "$FILENAME" == .env.* ]]; then
    REASON="'.env' files contain secrets and must not be edited by AI agents."
fi

if [[ -z "$REASON" ]] && [[ "$FILENAME" == *.pem || "$FILENAME" == *.key || "$FILENAME" == *.p12 ]]; then
    REASON="'$FILENAME' is a cryptographic credential file. Never modify directly."
fi

# --- Apple-specific credentials ---
if [[ -z "$REASON" ]] && [[ "$FILENAME" == *.p8 ]]; then
    REASON="'$FILENAME' is an Apple API key. Never modify — regenerate from App Store Connect if needed."
fi

if [[ -z "$REASON" ]] && [[ "$FILENAME" == *.mobileprovision || "$FILENAME" == *.cer ]]; then
    REASON="'$FILENAME' is an Apple provisioning file. Manage via Xcode or Fastlane Match, not directly."
fi

# --- Lock and generated files ---
if [[ -z "$REASON" ]] && [[ "$FILENAME" == "Package.resolved" ]]; then
    REASON="'Package.resolved' is auto-generated by SPM. Let Xcode or 'swift package resolve' manage it."
fi

if [[ -z "$REASON" ]] && [[ "$FILENAME" == "Podfile.lock" ]]; then
    REASON="'Podfile.lock' is auto-generated by CocoaPods. Run 'pod install' to update it."
fi

# --- Xcode project file ---
if [[ -z "$REASON" ]] && [[ "$FILENAME" == "project.pbxproj" ]]; then
    REASON="'project.pbxproj' is managed by Xcode. Direct edits cause merge conflicts and corruption. Make changes through Xcode instead."
fi

# --- Fastlane auth configs ---
if [[ -z "$REASON" ]] && [[ "$FILE_PATH" == */fastlane/Matchfile || "$FILE_PATH" == */fastlane/Appfile ]]; then
    REASON="'$FILENAME' is a Fastlane auth config containing sensitive credentials. Do not modify directly."
fi

# If no protected pattern matched, allow
if [[ -z "$REASON" ]]; then
    exit 0
fi

# Block the operation
jq -n --arg reason "$REASON" '{
  "hookSpecificOutput": {
    "hookEventName": "PreToolUse",
    "permissionDecision": "deny",
    "permissionDecisionReason": $reason
  }
}'

exit 0
